# Generated by Django 5.1 on 2024-09-25 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=70)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Tulsipur', 'Tulsipur'), ('Puythan', 'Puythan'), ('Nepaljung', 'Nepaljung'), ('Rolpa', 'Rolpa'), ('Dharan', 'Dharan'), ('Dhankuta', 'Dhankuta'), ('Bhaktpur', 'Bhaktpur'), ('lalitpur', 'lalitpur'), ('kathamandu', 'kathamandu'), ('Pokhara', 'Pokhara'), ('Bardia', 'Bardia'), ('Lamjung', 'Lamjung'), ('salyan', 'salyan'), ('DANG', 'DANG'), ('Rukum', 'Rukum')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
