# Generated by Django 5.1 on 2024-09-25 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
        migrations.RemoveField(
            model_name='product',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='state',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.CharField(choices=[('M', 'MObile'), ('L', 'Laptop'), ('T', 'Top wear'), ('B', 'Bottom wear')], default=False, max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Discounted_price',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(default=False, upload_to='media/Prodduct_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='Title',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=False),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=50)),
                ('Quantity', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=70)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Nepaljung', 'Nepaljung'), ('Bhaktpur', 'Bhaktpur'), ('Tulsipur', 'Tulsipur'), ('Dharan', 'Dharan'), ('Pokhara', 'Pokhara'), ('Puythan', 'Puythan'), ('lalitpur', 'lalitpur'), ('Rukum', 'Rukum'), ('kathamandu', 'kathamandu'), ('DANG', 'DANG'), ('Lamjung', 'Lamjung'), ('salyan', 'salyan'), ('Dhankuta', 'Dhankuta'), ('Bardia', 'Bardia'), ('Rolpa', 'Rolpa')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Acceppted', 'Accepted'), ('On The Way', 'On The Way'), ('Deivered', 'Deivered'), ('Cancel', 'Cancel'), ('Packed', 'Packed')], default='Pending', max_length=40)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap.customer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap.product')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
